#!/bin/bash
set -e

if [[ "$#" -lt "1" ]]; then
        echo "Usage: $0 <domain name>"
        exit 0
fi

DOMAIN=$1
DOMAINDIR="/etc/letsencrypt/keys/${DOMAIN}"

python ~/contrib/acme-tiny/acme_tiny.py \
	--account-key /etc/letsencrypt/account.key \
	--csr "${DOMAINDIR}/cert.csr" \
	--acme-dir /etc/letsencrypt/challenges/ \
	> "${DOMAINDIR}/signed.crt"

wget -O - https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > "${DOMAINDIR}/intermediate.pem"
cat "${DOMAINDIR}/signed.crt" "${DOMAINDIR}/intermediate.pem" > "${DOMAINDIR}/chained.pem"
certtool --verify-chain < "${DOMAINDIR}/chained.pem"
